# 一个workflow，名为deploy to tengxunyun
name: 同步至云服务器

on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - main

jobs:
  build: # 构建job
    runs-on: ubuntu-latest # 跑workflow的服务器系统
    steps: # job的一系列动作
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        # 选择一个action，可以理解为若干 steps.run，有利于代码复用
        uses: actions/checkout@master
      # 部署到腾讯云服务器
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'   #ssh user name
          server: '${{ secrets.IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.TOKEN }} #引用之前创建好的secret
          local_path: './*'  # 对应我们项目build的文件夹路径
          remote_path: '/www/wwwroot/uptime.seeyue.top/test'

